# Generated by Django 4.0.3 on 2023-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20221214_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='group',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default='bronze', max_length=10),
        ),
    ]
